# Generated by Django 4.2.3 on 2023-07-14 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=24, verbose_name="Ім'я")),
                ('middle_name', models.CharField(max_length=24, verbose_name='По батькові')),
                ('last_name', models.CharField(max_length=24, verbose_name='Прізвище')),
                ('position', models.CharField(max_length=48, verbose_name='Посада')),
                ('date_of_receipt', models.DateTimeField(auto_now=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('boss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.worker', verbose_name='Начальник')),
            ],
        ),
    ]
