# Generated by Django 4.2.3 on 2023-07-14 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name_plural': 'Працівник'},
        ),
    ]
